export const LOGO_LIST_REQUEST = 'LOGO_LIST_REQUEST';
export const LOGO_LIST_SUCCESS = 'LOGO_LIST_SUCCESS';
export const LOGO_LIST_FAIL = 'LOGO_LIST_FAIL';

export const LOGO_DETAILS_REQUEST = 'LOGO_DETAILS_REQUEST';
export const LOGO_DETAILS_SUCCESS = 'LOGO_DETAILS_SUCCESS';
export const LOGO_DETAILS_FAIL = 'LOGO_DETAILS_FAIL';

export const LOGO_SAVE_REQUEST = 'LOGO_SAVE_REQUEST';
export const LOGO_SAVE_SUCCESS = 'LOGO_SAVE_SUCCESS';
export const LOGO_SAVE_FAIL = 'LOGO_SAVE_FAIL';

export const LOGO_DELETE_REQUEST = 'LOGO_DELETE_REQUEST';
export const LOGO_DELETE_SUCCESS = 'LOGO_DELETE_SUCCESS';
export const LOGO_DELETE_FAIL = 'LOGO_DELETE_FAIL';
